### PR TITLE
Between "full" and "star" textFormat options

### PR DESCRIPTION
**Pull request by DarthTrevis**
This code adds another textFormat option ("simple") where:

- the pvalues below 0.01 are shown as lower than a power of ten (up to 1e-5)
- the performed test name can be shown or not.

I wrote this to have more flexibility between the "full" and "star" textFormat options.
A "showTestName" (default True) parameter is added to add_stat_annotation, only used for "simple" textFormat.

It's available if anyone else might benefit from it.

### CODE REVIEW

**Comment by DarthTrevis** [comment]
The strings displayed and the thresholds can now be defined for this "simple" format also, with the same pattern as for "star".

**Comment by webermarcolivier** [comment]
Thanks for the contribution!

I have one question, what is the advantage of using `object()` against `None` as default value?

**Comment by DarthTrevis** [comment]
Well, thanks for reviewing !

The idea is that you can better show that you do have default values with `=DEFAULT` and also allow to set to `None`

Technically, `None` would work too, but it could seem that by default the function does not apply formatting or have thresholds, which it does. And what if someone actually wants no formatting?

Since we would want them to be different for each `TextFormat` (without having twice as many function parameters with explicit defaults), these parameters can be used for any case.

Using this, someone looking only at the function definition will see there is a default formatting that will be applied if nothing is passed and can then look further to check what it is if necessary.

**Comment by webermarcolivier** [comment]
That makes sense, thanks for the explanation.

**Pull request merged**
